// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZQuaca0BdKHwMvocDMHn6INj13GkYAFQ',
    appId: '1:726812145169:web:d7428ea358a3289b4523b0',
    messagingSenderId: '726812145169',
    projectId: 'newsapp-24538',
    authDomain: 'newsapp-24538.firebaseapp.com',
    storageBucket: 'newsapp-24538.firebasestorage.app',
    measurementId: 'G-EWVX70ZGE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxc2pebXJTP2P-xX3ysfxt9rsPPmjpg3w',
    appId: '1:726812145169:android:b471804ddb1d570f4523b0',
    messagingSenderId: '726812145169',
    projectId: 'newsapp-24538',
    storageBucket: 'newsapp-24538.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkg6F5q-mUm_4IKSplxhBgwFdsI01gmY8',
    appId: '1:726812145169:ios:bbff18f1e7c489f74523b0',
    messagingSenderId: '726812145169',
    projectId: 'newsapp-24538',
    storageBucket: 'newsapp-24538.firebasestorage.app',
    androidClientId: '726812145169-lm5m9neu73cnh5p48vai5nhveb7nod54.apps.googleusercontent.com',
    iosClientId: '726812145169-83bahva3ud4c3oln4a95l6sgg7tn5fr8.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkg6F5q-mUm_4IKSplxhBgwFdsI01gmY8',
    appId: '1:726812145169:ios:bbff18f1e7c489f74523b0',
    messagingSenderId: '726812145169',
    projectId: 'newsapp-24538',
    storageBucket: 'newsapp-24538.firebasestorage.app',
    androidClientId: '726812145169-lm5m9neu73cnh5p48vai5nhveb7nod54.apps.googleusercontent.com',
    iosClientId: '726812145169-83bahva3ud4c3oln4a95l6sgg7tn5fr8.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZQuaca0BdKHwMvocDMHn6INj13GkYAFQ',
    appId: '1:726812145169:web:b94aa59fc7679cb64523b0',
    messagingSenderId: '726812145169',
    projectId: 'newsapp-24538',
    authDomain: 'newsapp-24538.firebaseapp.com',
    storageBucket: 'newsapp-24538.firebasestorage.app',
    measurementId: 'G-6X9J9NGSTP',
  );
}
